from __future__ import annotations
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from .config import settings
from .schemas import TriageResult, PatientIntake, Vitals
from .severity_color import severity_color

os.makedirs(settings.pdf_dir, exist_ok=True)


def render_triage_pdf(
    path: str,
    intake: PatientIntake,
    vitals: Vitals,
    result: TriageResult,
) -> str:
    doc = SimpleDocTemplate(path, pagesize=A4, title="Triage Report")
    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h2 = styles["Heading2"]
    body = styles["BodyText"]
    body.fontSize = 10
    body.leading = 14

    flow = []
    flow.append(Paragraph("RuralCare Triage Report", h1))
    flow.append(Paragraph(datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"), body))
    flow.append(Spacer(1, 12))

    flow.append(Paragraph("Patient", h2))
    pdata = [
        ["Name", intake.name or "—"],
        ["Age", str(intake.age) if intake.age else "—"],
        ["Sex", intake.sex or "—"],
        ["Phone", intake.phone or "—"],
        ["Village", intake.village or "—"],
        ["Language", intake.language],
    ]
    t = Table(pdata, colWidths=[90, 380])
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0fdf4")),
    ]))
    flow.append(t)
    flow.append(Spacer(1, 10))

    flow.append(Paragraph("Vitals", h2))
    vdata = [
        ["HR (bpm)", vitals.heartRate or "—"],
        ["BP (mmHg)", f"{vitals.systolic or '—'}/{vitals.diastolic or '—'}"],
        ["SpO₂ (%)", vitals.spo2 or "—"],
        ["Temp (°C)", vitals.temperatureC or "—"],
        ["RR (/min)", vitals.respiratoryRate or "—"],
        ["Glucose (mg/dL)", vitals.bloodGlucose or "—"],
    ]
    t2 = Table(vdata, colWidths=[90, 380])
    t2.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
    ]))
    flow.append(t2)
    flow.append(Spacer(1, 12))

    sev_color = severity_color(result.severity)
    flow.append(Paragraph(f"Severity: <font color='{sev_color}'><b>{result.severity}</b></font>", h2))
    flow.append(Paragraph(f"Confidence: {int(result.confidence * 100)}%", body))
    flow.append(Spacer(1, 6))

    flow.append(Paragraph("Chief complaint", h2))
    flow.append(Paragraph((intake.chiefComplaintText or "—").replace("\n", "<br/>"), body))
    flow.append(Spacer(1, 8))

    flow.append(Paragraph("Rationale", h2))
    flow.append(Paragraph(result.rationale, body))
    flow.append(Spacer(1, 8))

    flow.append(Paragraph("Diagnosis suggestions", h2))
    for d in result.diagnosisSuggestions:
        flow.append(Paragraph(f"• {d}", body))
    flow.append(Spacer(1, 6))

    flow.append(Paragraph("First aid advice", h2))
    for d in result.firstAid:
        flow.append(Paragraph(f"• {d}", body))
    flow.append(Spacer(1, 6))

    flow.append(Paragraph("Referral", h2))
    flow.append(Paragraph(
        f"Level: <b>{result.referral.level}</b><br/>"
        f"Facility: {result.referral.facility or '—'}<br/>"
        f"Rationale: {result.referral.rationale}",
        body,
    ))

    if result.warnings:
        flow.append(Spacer(1, 6))
        flow.append(Paragraph("Warnings", h2))
        for w in result.warnings:
            flow.append(Paragraph(f"⚠ {w}", body))

    flow.append(Spacer(1, 18))
    flow.append(Paragraph(
        "<i>This report is generated by an AI triage assistant. It does not replace a qualified clinician. "
        "Always confirm diagnosis and treatment with a licensed medical professional.</i>",
        body,
    ))

    doc.build(flow)
    return path
